name: Lint & Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    uses: SiaFoundation/workflows/.github/workflows/go-test.yml@22e56c0750c0febb09784caa01c60021e0b5f111 # master
    with:
      try-build: false
