name: Lint & Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    uses: SiaFoundation/workflows/.github/workflows/go-test.yml@3d496e2845d325cc657cedfa8ec7aba60953a1c3 # master
    with:
      try-build: false
